# Generated by Django 5.2 on 2025-04-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstatisticaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('total_ampolas_abertas', models.IntegerField(default=0)),
                ('total_ampolas_vencidas', models.IntegerField(default=0)),
                ('total_vacinacoes', models.IntegerField(default=0)),
                ('total_notificacoes_enviadas', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Estatística Diária',
                'verbose_name_plural': 'Estatísticas Diárias',
            },
        ),
    ]
