# Generated by Django 5.2 on 2025-04-13 03:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoVacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('tempo_validade_horas', models.IntegerField(help_text='Tempo de validade em horas após a abertura da ampola')),
            ],
            options={
                'verbose_name': 'Tipo de Vacina',
                'verbose_name_plural': 'Tipos de Vacinas',
            },
        ),
        migrations.CreateModel(
            name='Ampola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_vencimento', models.DateTimeField()),
                ('doses_iniciais', models.IntegerField(default=10)),
                ('doses_restantes', models.IntegerField(default=10)),
                ('tipo_vacina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ampolas', to='vacinas.tipovacina')),
            ],
            options={
                'verbose_name': 'Ampola',
                'verbose_name_plural': 'Ampolas',
            },
        ),
        migrations.CreateModel(
            name='Vacinacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', models.CharField(max_length=100)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('dose', models.IntegerField(default=1)),
                ('ampola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacinacoes', to='vacinas.ampola')),
            ],
            options={
                'verbose_name': 'Vacinação',
                'verbose_name_plural': 'Vacinações',
            },
        ),
    ]
