# Generated by Django 5.2 on 2025-04-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacinas', '0002_alter_vacinacao_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacinacao',
            name='pessoa',
            field=models.CharField(max_length=100),
        ),
    ]
